name: Secret-Test

on:
  push:
    branches:
      - main

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zeige secret_message (maskiert)
        run: echo "Das Secret ist ${{ secrets.GEHEIME_NACHRICHT }}"
